# Generated by Django 4.1.7 on 2024-03-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwkapp', '0003_rename_authorname_author_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default=None, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
