# Generated by Django 4.1.7 on 2024-03-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwkapp', '0002_rename_name_author_authorname_remove_author_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorName',
            new_name='author',
        ),
    ]
